# The GCS ID, which must match the parameters on the PixHawk.
gcs_id: 1

# The normal waypoint speed in m/s. This value is used
# as the cruising speed toward the next waypoint, unless
# overridded in the waypoint altitude encoding.
#
# This value is not used when approaching or escaping
# a cone under MANUAL mode. Instead, the PWM limits,
# below, are used as the maximum range.
normal_speed: 3.0

# The minimum cone appraoch speed in m/s. This value is
# used when driving in GUIDED mode toward a cone. This
# value is not used when driving in MANUAL mode. Instead,
# the PWM limits, below, as used.
min_speeed: 0.1

# The maximum turning velocity, in rad/sec, when using
# GUIDED mode to approach a cone. It is multipled by
# the turning factor calculated from the proporational
# constant, later in this configuration.
#
# This value is not used when using the throttle to
# approach the cone. Instead, the PWM limits are used
# as the maximum range.
max_turning: 5.0

# The throttle PWM range.
throttle_neutral: 1500
throttle_fwd_min: 1500
throttle_fwd_max: 2000
throttle_reverse_min: 1500
throttle_reverse_max: 1000

# The steering PWM range.
steering_neutral: 1500
steering_left_max: 1000
steering_right_max: 2000

# Sets whether to use commanded velocity under GUIDED mode
# or throttle control under MANUAL mode. If false, use
# GUIDED mode, if true, use MANUAL R/C override.
cone_approach_use_throttle: true

# The constant used to determine the cone approach speed as
# a fraction of either the cone cruise speed or the cone
# throttle range. This is multiplied by the distance to
# determine the speed factor from 0 to 1.
cone_approach_k_speed: 0.02

# The proportional constant used to determine the turn rate
# when approaching, as a fraction of the maximum turning.
cone_approach_k_turning: 1.25

# The number of seconds in which the robot must touch the cone
# or the attempt will be abandoned.
cone_timeout_seconds: 60

# The proportional constant used to determine the fraction
# of the cone waypoint speed to use when escaping from a
# cone. This times the heading difference to the next
# waypoint is used as the speed fraction from 0 to 1.
escape_k_speed: 0.1

# The proportional constant used to determine the fraction
# of the maximum turning to use when backing up from a
# cone. This times the heading difference gives the fraction
# of maximum turning to use.
escape_k_turning: 0.7

# The maximum tolerance in heading error in radians before
# deciding that the robot has turned sufficiently toward
# the next cone. A value of 0.1 rad is about 6 degrees.
escape_angle_tolerance: 0.15

# The horizontal field-of-view of the camera, in degrees.
horz_fov: 70.0

# The horizontal field-of-view of the camera, in pixels.
horz_pixels: 640
